version: "3.8"

services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.4
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-XX:UseSVE=0
      - CLI_JAVA_OPTS=-XX:UseSVE=0
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 2g
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:8.17.4
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://es01:9200
    mem_limit: 1g
    ports:
      - 5601:5601
    depends_on:
      - es01
    networks:
      - elastic

  bootstrap:
    image: alpine
    container_name: es-bootstrap
    privileged: true
    pid: "host"
    command: sh -c "sysctl -w vm.max_map_count=262144 && sleep infinity"
    restart: unless-stopped

volumes:
  esdata01:

networks:
  elastic:
