spring:
  application:
    name: reverse-geocoding-api
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/t1100555
    username: t1100555
    password:
    hikari:
      maximum-pool-size: 10

elasticsearch:
  host: localhost
  port: 9200
  scheme: http
  connectTimeout: 5000
  socketTimeout: 60000
  maxRetryTimeoutMillis: 60000
  indexSettings:
    numberOfShards: 1
    numberOfReplicas: 1

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /
    operations-sorter: method
    tags-sorter: alpha

server:
  port: 8080
  servlet:
    context-path: /
  tomcat:
    max-threads: 200
    min-spare-threads: 10
    max-connections: 10000
